project:
  type: website
  output-dir: docs
  
website:
  page-footer: Copyright 2024 | <a href="https://marce10.github.io">Marcelo Araya-Salas</a>
  title: "OTS TBCP 2024"
  search: true
  site-url: https://marce10.github.io/OTS_TBCP_2024/
  repo-url: https://github.com/maRce10/OTS_TBCP_2024/
  navbar:
    background: white
    right:
      - icon: github
        href: https://github.com/maRce10/OTS_TBCP_2024
        aria-label: GitHub
    left:
      - href: index.qmd
        text: " "
      # - text: "Programa"
      #   href: program.qmd
      - text: "Tutorials"
        menu:
        - text: "R basics"
          href: r_basics.qmd
        - text: "Import and format data in R"
          href: importing_data.qmd
        - text: "Simulating data"
          href: como_simular_datos.qmd
        - text: "Regresion models"
          href: modelos_de_regresion.qmd
        # - text: "Estadística tradicional como regresión"
          # href: estadistica_tradicional_regresion.qmd
        - text: "Elegant graphs with ggplot2"
          href: ggplot2.qmd
        #- text: "Reportes dinámicos"
        #  href: reportes_dinamicos.qmd
      - text: "Course prep"
        href: course_prep.qmd
      - text: "Sharing code"
        href: https://codefile.io/f/inMsojTFoN
      - text: "Instructor"
        href: instructor.qmd

toc: true
toc-depth: 2
toc-location: left
toc-title: Contents
number-sections: true
code-line-numbers: false
highlight-style: pygments
code-overflow: wrap
code-copy: true
date: today
lang: en
format:
  html:
    css: styles.css
    toc: true
    df-print: kable
    code-fold: show
    code-tools: true
    link-external-icon: false
    link-external-newwindow: true  
      
editor: visual